### ISSUE TITLE
PSČ autocomplete je pomalý

### ISSUE THREAD

**Issue by jirihelmich** [HlidacStatu/Volicsky-Prukaz#14]
Tak pomalý, že mi na chvíli zamrzne browser (Chrome 61, MacOS). A stejně nenapovídá moc dobře :-)

Buď bych ho dal úplně pryč nebo místo něj https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

**Comment by romulusCZ** [comment]
Na WIN to jede úplně bez problémů. No, pokud by to hledalo jen v PSČ, půjde to zrychlit. Ale chtěl jsem, aby to hledalo kombinace PSČ+obec, protože jedno PSČ může mít více obcí a opačně, v jednom městě je několik PSČ.
Ten form od Googlu odporuje tomu neodesílání dat na server, které se tam někde slibuje.
Můžeme to rozdělit a zadávat zvlášť Město a PSČ teda asi a validovat jen výslednou kombinaci.

**Comment by romulusCZ** [comment]
Pryč to úplně dávat nechci, protože bych rád měl jednoznačnou identifikaci pro výběr adresy úřadu.
