### ISSUE TITLE
Spojení polí Ulice + číslo důmu

### ISSUE THREAD

**Issue by jakubboucek** [HlidacStatu/Volicsky-Prukaz#17]
Je technický důvod, proč musí být rozdělena adresa na Ulice a Číslo domu? 

Jde o to, že autofillery toto rozdělení nepoužívají a pak je nejde použít. Pokud není potřeba pro funkci nástroje rozdělení těchto dvou polí (a nepostačuje jejich případné rozsehnutí regulárním výrazem), navrhuji jejich sloučení do jednoho.

**Comment by michalblaha** [comment]
maji to tak na SK, nemenili jsme to z duvodu rychlejsiho nasazeni. Je to minoritni problem. Pokud to upravite napric aplikaci, budeme radi.

**Comment by michalkleiner** [comment]
Jsem pro slouceni, jelikoz treba novozelandske adresy pouzivaji cislo domu pred nazvem ulice, takze jsem informace zapsal naopak, ale bylo by fajn to spojit.

**Comment by woodarius** [comment]
@jakubboucek upraveno v návrhu nové verze, díky za podnět!
