### ISSUE TITLE
Umisteni podpisu v PDF

### ISSUE THREAD

**Issue by rpliva** [HlidacStatu/Volicsky-Prukaz#21]
Pri "zapsani" podpisu v prohlizeci, dojde k jeho umisteni tesne pod text adresy a tesne k pravemu okraji stranky.

![image](https://user-images.githubusercontent.com/11376905/33502114-28cb4342-d6df-11e7-9133-2c4e6c910402.png)

![image](https://user-images.githubusercontent.com/11376905/33502122-2d9d14a4-d6df-11e7-918a-94b97528a622.png)

Je to drobnost, ale lepe by vypadalo, kdyby byl podpis posunut nize na uroven data a vice od praveho kraje

**Comment by jakubboucek** [comment]
Podle mě je celý podpis jen kravina. Při tisku a posílání poštou se udělá ručně, při použití DS je podpis právně nahrazen úkonem podání přes DS.
