### ISSUE TITLE
Aktualizace pro prezidentské volby

### ISSUE THREAD

**Issue by molcanf** [HlidacStatu/Volicsky-Prukaz#28]
Upravit voličský průkaz pro prezidentské volby

**Comment by jakubboucek** [comment]
Ale to už je, viz brach [prezident2018](https://github.com/HlidacStatu/Volicsky-Prukaz/tree/prezident2018). Ale vidím, že tam není ještě upraveno readme a záhlaví.

**Comment by molcanf** [comment]
Omluva, měl jsem to sem napsat ;-) Potřebujeme trochu vyzkoušet, jak tu fungují Issues...;-)

**Comment by jakubboucek** [comment]
No, ale tak i tahle issue slavila úspěch

**Comment by jakubboucek** [comment]
Aha, ok. Ve volném čase si s tím hraju, trochu refaktoruju a čistím kód a tak. Otázkou ale je, jestli na tom teď taky nějak usilovně nepracujete, abychom nedošli do konfliktu. 

@molcanf, @michalblaha: Chystáte se appku jen upravit jako doposud, nebo udělat nějaké zásadní změny?

**Comment by zzen** [comment]
mezitím už dávno vyřešeno, zavírám
