### ISSUE TITLE
Logika aplikace - zmeny oproti SK

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Volicsky-Prukaz#3]
Zákon říká dva způsoby, jak lze již ode dne vyhlášení voleb požádat obecní úřad příslušný podle místa trvalého pobytu voliče o vydání voličského průkazu.

1) osobně,  v tomto případě není písemná žádost vyžadována. Toto je scénář, který neřešíme

2) podáním doručeným nejpozději 7 dnů přede dnem voleb, tj. do 13. října 2017, příslušnému obecnímu úřadu
    2a) v listinné podobě opatřené úředně ověřeným podpisem voliče;
    2b) v elektronické podobě zaslané prostřednictvím datové schránky.

3) Naše aplikace sesbírá údaje o voliči-žadateli (plné jméno, datum narození, trvalý pobyt, volitelně telefon) , z něj odvodí adresu (poštovní i datovou schránku) obecního úřadu

4) Dále se zeptá na způsob, jakým má být voličský průkaz doručen
  4a) volič si ho převezme osobně na obecním úřadě. Tím pádem my to neřešíme
  4b) převezme osoba, které udělím plnou moc. v tom případě sesbíráme údaje o této osobě a vygenerujeme plnou moc (viz vzor příloha)
  4c) zaslat na adresu místa mého trvalého pobytu. 
  4d) žádám zaslat na jinou adresu: zeptáme se na tuto adresu

5) vygenerujeme PDF se žádosti o voličský průkaz dle údaje z 2), 3) a 4), případně také plnou moc (4b))

Volič žadatel pak už sám, bez naší pomoci buď PDF odešle datovkou, anebo ho vytiskne, nechá ověřit a zašle poštou.

Vzory dokumentu jsou jen schematicky (texty), grafiky to muze byt v PDF jinak, jen hrube formatovani. 
[plna-moc-volby-2017.docx](https://github.com/HlidacStatu/VolebniPrukaz/files/1290953/plna-moc-volby-2017.docx)
[vzor-zadosti-o-vp.docx](https://github.com/HlidacStatu/VolebniPrukaz/files/1290954/vzor-zadosti-o-vp.docx)

**Comment by PavelVanecek** [comment]
V SK verzi je i logika o žádost o volbu poštou. Taková možnost v ČR neexistuje, že?

>Termín na podávanie žiadostí o <b>voľbu poštou</b> zo zahraničia ...

**Comment by michalblaha** [comment]
neexistuje,

**Comment by stepnivlk** [comment]
> 3. Naše aplikace sesbírá údaje o voliči-žadateli (plné jméno, datum narození, trvalý pobyt, volitelně telefon) , z něj odvodí adresu (poštovní i datovou schránku) obecního úřadu
> 4. Dále se zeptá na způsob, jakým má být voličský průkaz doručen
4a) volič si ho převezme osobně na obecním úřadě. Tím pádem my to neřešíme

To znamena, pokud se volic rozhodne pro 4a) tak je cely krok 3 zbytecny ze? to mi prijde jako ne uplne stastne user experience. Osobne bych asi v uplne prvnim kroku jasne a strucne definoval pravidla za kterych aplikace ma smysl.

**Comment by pykaso** [comment]
Tak vidím, že moje kostra v angularu už asi není potřebná. Nějak se mi ta SK verze netrefila do noty.

**Comment by PavelVanecek** [comment]
@pykaso myslím, že úprava SK verze bude rychlejší. Sice se mi ten kód postavený nad jQuery taky nelíbí, ale nemáme do voleb příliš mnoho času ...

**Comment by pykaso** [comment]
@stepnivlk Já to chápu tak, že si pomocí 4a) může připravit alespoň tu žádost co by stejně musel naspat.

**Comment by pykaso** [comment]
BTW ta moje kostra je na http://volby.pykaso.net
Vytvorena je pouze jedna varianta, vzdy prvni tlacitko ve formu.
Udelano pomoci nested views. Kazdy krok ma vlastni view v samostatnem souboru.
