### ISSUE TITLE
Chybi mesto podpisu pri podepsani zadosti se zplnomocnenou osobou

### ISSUE THREAD

**Issue by rpliva** [HlidacStatu/Volicsky-Prukaz#30]
Pri vyplneni podpisu u zadosti, kde volicsky prukaz vyzvedne zplnomocnena osoba, neni vyplneno mesto, ackoli ve formulari vyplneno bylo. V zadosti je pouze `V `

![image](https://user-images.githubusercontent.com/11376905/33528866-95995592-d868-11e7-837d-43cc4a8bf692.png)

Duvodem je to, ze se vzdy doplnuje pouze mesto z adresy pro doruceni volicskeho prukazu, ktere se pri prevzeti zplnomocnenou osobou nevyplnuje

**Comment by woodarius** [comment]
test ok, přidáno no aktuální verze, díky @rpliva
