### ISSUE TITLE
Drobné textové a UI změny

### ISSUE THREAD

**Issue by sigy** [HlidacStatu/Volicsky-Prukaz#33]
Navrhuji pár drobných změn, díky kterým by průvodce mohl být snáz použitelnější a pochopitelnější.

## Homepage

- Jde o detail, ale pomohlo by, pokud bychom hornímu nadpisu dali větší mezeru shora (aby nesplýval s hlavičkou) a vycentrovali jsme tlačítko pro spuštění (aby vyniklo rozbitím rytmu zarovnání).
- V odrážkovém seznamu bych zkusil přeformulovat text na: 

> - Vytvoření žádosti trvá asi 2 minuty.
> - Žádost je vytvořena pouze na vašem počítači – žádné ze zadaných osobních údajů se z vašeho počítače nikam neodesílají.
> - Vytvoření žádosti funguje i bez připojení k internetu.

## V prvním kroku žádosti

- Místo „Vyberte si z možností“ by bylo dobré formulář nadepsat názvem (pokud by například někdo přišel přímo na tuhle URL).
- Oba z checkboxů (první kolo voleb, druhé kolo voleb) jsou bez tečky na konci a pomohlo by doplnit data, kdy se budou konat.
- „Chci zaslat voličský průkaz do vlastních rukou“ – šel by odkaz na bližší informace (kam ho pošlou, stojí to něco)?
- „Pro průkaz mi a úřad přijde zplnomocněná osoba“ – máme šablonu plné moci (respektive co to přesně obnáší)?
- Osobní vyzvednutí průkazu – kdy a kde?
- Místo tří tlačítek bych se nebál nového nadpisu „Způsob doručení“ s třemi radio buttony (včetně stručného vysvětlení). U tlačítek je matoucí co bude další akce (u prvních dvou se odešle, u třetího dostanu další informace).

## Formulář

- Chybí nadpis formuláře (abych věděl kde jsem).
- Popis by stálo za to formulovat víc fakticky a méně paranoidně (viz výše).
- Závorky s doplňujicím vysvětlením jsou šedé pouze u rodného příjmení (hádám, že mají být všude).
- Číslo domu popisné nebo orientační?

Můžu to kdyžtak naházet do screenshotů…

**Comment by woodarius** [comment]
@sigy na nové podobě už společně pracujeme, tady si dovolím pro přehlednost zavřít.
