### ISSUE TITLE
Po vyplnění podpisu se ho nemůžu zbavit

### ISSUE THREAD

**Issue by maral** [HlidacStatu/Volicsky-Prukaz#34]
Vyplnil jsem podpis, ale pak si to rozmyslel, protože potřebuji ověřit podpis na poště. Šel jsem zpět na krok 3 a zvolil "vystisknout bez podpisu" a podpis v PDF byl.

**Comment by woodarius** [comment]
@maral validujeme nutnost přítomnosti podpisu a revidujeme postup vyplňování, díky za podnět.

**Comment by zzen** [comment]
podpis v budoucích verzích nebudeme nabízet (při odeslání datovou schránkou není potřeba, při odeslání poštou je potřeba poskytnout ověřený podpis, tedy nejspíše podepsat před notářem/úředníkem osobně)
