### ISSUE TITLE
Chybějící čárka

### ISSUE THREAD

**Issue by adamheinrich** [HlidacStatu/Volicsky-Prukaz#35]
Díky za fajn projekt!

Stávající aplikace pro volbu prezidenta obsahuje malou chybku (chybějící čárka před "a to"), zároveň je věta poněkud kostrbatá:

> žádám o vydání voličského průkazu pro volby prezidenta České republiky a to první kolo 12. a 13. ledna 2018

Lepší formulace by byla: "žádám o vydání voličského průkazu pro volby prezidenta České **republiky, a to pro** první kolo 12. a 13. ledna 2018"

**Comment by zzen** [comment]
už asi není podstatné, zavírám
