### ISSUE TITLE
Formulář doručovací adresy by měl obsahovat více polí

### ISSUE THREAD

**Issue by adamheinrich** [HlidacStatu/Volicsky-Prukaz#36]
Pokud chci doručit voličský průkaz na velvyslanectví, musím jeho název zadat jako součást ulice. Podobný problém by nastal, pokud bych chtěl průkaz poslat např. do zaměstnání.

Formulář pro adresu by tedy měl obsahovat ještě jedno volitelné pole.

**Comment by woodarius** [comment]
@adamheinrich zohledněno v novém návrhu, díky za podnět!
