### ISSUE TITLE
Je zájem předelat app senátní volby 2018?

### ISSUE THREAD

**Issue by jakubboucek** [HlidacStatu/Volicsky-Prukaz#37]
Vyřizuji si voličský průkaz na volby do senátu a koukám, že tato app zamrzla na volbách na hrad. Má to cenu předělávat, je o to zájem?

(oprava, nemyslím komunálky, kde VP nelze, ale senátní volby)

**Comment by peterppp** [comment]
Ta appka je potrebna ako v Cechach tak aj aj na Slovensku.
Samozrejme to ma vyznam vylepsovat kedze sa to bude pouzivat znova a znova.

**Comment by zzen** [comment]
Senátní volby jsou pryč, ale na volby do EP tento rok to předěláme.
