### ISSUE TITLE
Odkaz na volební kalkulačku

### ISSUE THREAD

**Issue by kokes** [HlidacStatu/Volicsky-Prukaz#39]
Nerozhodnutým může pomoci volební kalkulačka (https://volebnikalkulacka.cz), která by mohla být nalinkovaná. Pokud bude anglická mutace, může se odkázat na anglickou kalkulačku, pokud bude letos připravená (https://electioncalculator.org).

**Comment by woodarius** [comment]
Odkaz přidán, anglická verze aktuálně ještě není funkční a nemá platný certifikát. Jakmile bude k dispozici tak určitě také přidáme.
