### ISSUE TITLE
Chyby z validátoru by neměly být vkládány do výsledného PDF

### ISSUE THREAD

**Issue by woodarius** [HlidacStatu/Volicsky-Prukaz#41]
Výstupy z validace adresy by neměly být vkládány do finálního PDF dokumentu. Toto zabraňuje manuální úpravě vstupů a výsledný PDF dokument je nepoužitelný. Validace mají uživatele upozorňovat že MOŽNÁ udělal chybu, ale pokud ji udělat chce, tak zklapnout a PDF poslušně vytisknout. Je to jeho PDF.

Příklad: "Adresa trvalého pobytu: , NEPODAŘILO SE NAČÍST OBEC, ČESKÁ REPUBLIKA"

**Comment by zzen** [comment]
@woodarius tohle už asi můžeš zavřít, ne?
