### ISSUE TITLE
Přidat nový vizuální styl

### ISSUE THREAD

**Issue by zzen** [HlidacStatu/Volicsky-Prukaz#45]
Je potřeba použít nové vizuální templaty (HTML&CSSka) od agentury Š+G, která předělává vizuální styl Hlídače státu a přestylovat s nimi stávající low-fidelity prototyp. Zdrojáky jsou k dispozici v [#volicske-prukazy](https://code4cz.slack.com/messages/CG2U4701K) Slack channelu.

**Comment by kokes** [comment]
Čau,
sem na dovolený, nemám tu úplně ideální technický zázemí, tak jen zkratkovitě a nezaverzovaně:

- pro rozběhání je potřeba `new.css` z toho templatu, ideálně i adresář `fonts`, obojí do rootu
- v původním HTML je linkován Bootstrap 4, ale ten Š+G template běží na bootstrapu 3.3.7, tak sem ho tam nalinkoval (včetně jQuery), ale nemám tam sha256 integritu
- použil jsem věci ze style guidu, kde to šlo, ale 1) ta `emphasized` třída taková dost agresivní, tak je otázka, jestli ji chcem použít
- ty taby jsem převzal z `new-test.html`, ale co sem do nich narval ty routy, tak se to nějak rozsypalo - jakože to vypadá cajk, ale při překlikávání se nemění styly - to asi protože tu místo odkazu je ta routa (a v ní nejsou ty properties, který to chce) - konkrétně to nepřidává classu active a taky to při bluru nezmění ten hover styl (šedé podbarvení)
- už to mám attachnuté a nechci to teď měnit :) - ty taby nejsou stylově svázané se zbytkem (jakozˇe fontem)

[index-new.html.zip](https://github.com/HlidacStatu/Volicsky-Prukaz/files/2989591/index-new.html.zip)

**Comment by zzen** [comment]
Bezva, dík @kokes! Já to dneska vezmu, přidám tu sha256 integritu, fixnu ty taby a otevřu na to pullrequest, kde to budem dál upravovat.

**Comment by zzen** [comment]
Jinak rychlá poznámka: sha256 integritu velmi jednoduše doděláš na https://www.srihash.org
