### ISSUE TITLE
Není jasné, co znamená, když není nalezeno PSČ u trvalého bydliště

### ISSUE THREAD

**Issue by SmallhillCZ** [HlidacStatu/Volicsky-Prukaz#51]
Já mám třeba PSČ 11800 a to není v seznamu. Chvíli mi trvalo přijít na to, co mám dělat - vždycky po zadání jen zmizelo :/

**Comment by SmallhillCZ** [comment]
Jo sry, nevšiml jsem si, že se to řešilo na Slacku. Issue ale nechávám, protože je to issue ;)

**Comment by woodarius** [comment]
@SmallhillCZ pro větší transparentnost komentář i tady: aktuálně pracujeme s omezenými daty úřadů a bez znalosti spádových oblastí vyhledáváme pomocí shody PSČ. Pokud spádový úřad nemá stejné PSČ jako uživatel, aktuálně jej neumíme přidělit.

Na získání lepších pracujeme.

**Comment by KamilZm** [comment]
@zzen @woodarius 
Teď jsem si s tím hrál a budeme to muset upravit. Nejde jen o dohledání OÚ. Jak píše @SmallhillCZ, tak pokud PSČ není v seznamu, tak tam jiné nelze zadat (autocomplete to zřejmě nedovolí) a pak není u uživatele vytištěno v žádosti u jeho trvalého pobytu a nemá šanci ho do té žádosti dostat.

**Comment by zzen** [comment]
@KamilZm tak možná rychlejší bude umravnit autocomplete aby dovolil cokoliv. Ale budeme to muset prehodit, naprostý souhlas.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KamilZm** [comment]
@zzen Vytahal jsem z adresních míst seznam všech PSČ a přidal ho jako zvláštní soubor pro našeptávač. Následně se v původním pokouším dohledat údaje o obecním úřadu. Viz pull request  https://github.com/HlidacStatu/Volicsky-Prukaz/pull/59
Ale to umravnění budeme i tak raději muset provést.

**Comment by KamilZm** [comment]
@SmallhillCZ Tohle by mělo být již vyřešeno. Seznam PSČ by měl být úplný a také by to mělo pustit zadat i nějaké jiné. Můžeš to prosím uzavřít?

**Comment by zzen** [comment]
@SmallhillCZ vzhledem k tomu že jsi autorem issue můžeš potvrdit že se již nevyskytuje a případně zavřít?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SmallhillCZ** [comment]
Funguje, boží.
