### ISSUE TITLE
Aplikace nefunguje v Microsoft Edge

### ISSUE THREAD

**Issue by KamilZm** [HlidacStatu/Volicsky-Prukaz#52]
Zobrazí se jen hlavička a patička stránky. Přikládám ukázku + stav konzole.
<img width="964" alt="2019-04-12_06h11_31" src="https://user-images.githubusercontent.com/7085032/56011980-91d0e580-5cea-11e9-84b8-cd7a662989d2.png">

**Comment by SmallhillCZ** [comment]
Můžeš pls zkusit https://volicsky-prukaz-git-fork-smallhillcz-euro2019.hlidacstatu.now.sh?

**Comment by KamilZm** [comment]
Je to bohužel stejné.
<img width="948" alt="2019-04-12_07h27_32" src="https://user-images.githubusercontent.com/7085032/56014199-7ff44000-5cf4-11e9-893e-c1ad172fbb7c.png">

**Comment by PetrFlegr** [comment]
volání filtru bez this. projde

`<strong>Datum narození:</strong> {{(userData.birthdate | dateCZ) || ''}} <br>`

![image](https://user-images.githubusercontent.com/17861678/56014458-be3e2f00-5cf5-11e9-9534-7d1747d75ecb.png)
