### ISSUE TITLE
Layout na mobilech potřebuje poladit

### ISSUE THREAD

**Issue by danrisingup** [HlidacStatu/Volicsky-Prukaz#6]
![bs_realios_mobile_iphone 6s-9 0](https://user-images.githubusercontent.com/13216478/30545588-5beef42e-9c8a-11e7-9a8c-2f1e14bc0489.jpg)
![bs_realdroid_mobile_samsung galaxy s8-7 0-1440x2960](https://user-images.githubusercontent.com/13216478/30545586-5bc03986-9c8a-11e7-81c7-91ab8215f7d9.jpg)
![bs_realdroid_mobile_google nexus 6p-7 0-1080x1920](https://user-images.githubusercontent.com/13216478/30545587-5bc7cfc0-9c8a-11e7-8295-aad8e5abefaf.jpg)

**Comment by peterppp** [comment]
banner s logom a "Parlamentni volby 2017" zaberaju vela miesta

**Comment by zzen** [comment]
Podle aktuálního oveření to vypadá že problém už je odstraněn
