### ISSUE TITLE
Mobilní design

### ISSUE THREAD

**Issue by zzen** [HlidacStatu/Volicsky-Prukaz#62]
Momentálně se na mobilu aplikace prakticky nedá použít… Urgentní!

**Comment by iBobik** [comment]
![251B40F0-847C-4E2B-AEA5-4363143C7C71](https://user-images.githubusercontent.com/614232/56794103-c033e200-680d-11e9-8fd5-dc5325750db5.png)

**Comment by iBobik** [comment]
Zacyklil jsem se v navigaci - kliknu na "Jsem občanem ČR a chci volit v ČR" a pak mě "Vytvořit písemnou žádost o průkaz" dostane k předchozímu tlačítku.

https://share.icloud.com/photos/0O6Hon4mcoY8CvCNg7zpf4OyQ
