### ISSUE TITLE
Špatně vyplnění úřadu dle PSČ

### ISSUE THREAD

**Issue by iBobik** [HlidacStatu/Volicsky-Prukaz#64]
Po vyplnění PSČ to načte úřad přilehlé vesnice, která sice je geograficky blíže a má stejné PSČ, ale nespadá k mé adrese.

![84E28B1C-3CEF-4F50-8BBC-A99AB2D90DA2](https://user-images.githubusercontent.com/614232/56794250-07ba6e00-680e-11e9-92e1-32ac93f6aa98.png)

Možná souvisí s #62.

**Comment by zzen** [comment]
cc @KamilZm - tohle už asi jinak než plnohodnotnou adresní validací nepůjde, že?

**Comment by iBobik** [comment]
Napadá mě, že by to pomohl řešit select box, kde můžu vybrat jiný úřad poblíž.

**Comment by KamilZm** [comment]
@zzen Ano, přesně tak.

**Comment by KamilZm** [comment]
@iBobik @zzen Resp. abych byl přesnější a mohl to zjistit - jaké PSČ jsi zadával? Na tom obrázku není vidět celé.

**Comment by iBobik** [comment]
Zadával jsem 73801

**Comment by KamilZm** [comment]
@iBobik Úprava je v [produkci,](https://volby.hlidacstatu.cz/) můžeš to prosím zkusit a pokud to bude OK, tak tohle uzavřít?
Kdybys byl tak hodný a zkusil to i v [připravované verzi](https://volby2.hlidacstatu.cz/), kde jsem do ovládacího prvku na výběr PSČ více sahal, byl bych rád.
PS: V produkci bude asi nutný CTRL+F5

**Comment by iBobik** [comment]
Obě fungují, ikdyž na mobilu to bylo peklíčko - #62. :-)

**Comment by KamilZm** [comment]
Díky moc.
