### ISSUE TITLE
Vraci spatne OU pro Hybralec

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/Volicsky-Prukaz#69]
Dobrý den,

chtěla jsem si přes vaše stránky vyplnit voličský průkaz na květnové volby. Trvalé bydliště mám v Jihlavě - konkrétně (adresa ve Slacku). Bohužel mi to vyhodilo, že můj obecní úřad je Hybrálec, což není správně. Je to na 100% Jihlava. Hybrálec je vesnice na opačném konci Jihlavy. Šlo by to opravit?

Děkuji
(kontakt ve Slacku)

**Comment by KamilZm** [comment]
Autorce byl odeslán e-mail s upřesňujícími dotazy.

**Comment by KamilZm** [comment]
Přišla odpověď, uživatelka používala ještě verzi bez těch statutárů, nyní je to OK. Lze to uzavřít.

--------------------
Od: Kamil Zmeškal
Komu: Š.
Re: Problém u aplikace pro voličský průkaz

Dobrý den,

děkuji za informace, navíc příznivé.

Jsme rádi, že jste využila naši aplikaci. 

S pozdravem

Kamil Zmeškal

---------- Původní e-mail ----------
Od:  Š.
Komu: Kamil Zmeškal
Datum: 29. 4. 2019 14:37:49
Předmět: Re: Problém u aplikace pro voličský průkaz

Dobrý den Kamile, 

vyplňovala jsem to 24.4. někdy před 10 ráno. A momentálně už to ukazuje správně. 

Díky Š.

---------- Původní e-mail ----------
Od: Kamil Zmeškal 
Komu: Š.
Datum: 29. 4. 2019 11:19:01
Předmět: Problém u aplikace pro voličský průkaz

Dobrý den,

děkuji za reakci na naši aplikaci. Chtěl bych Vás požádat o upřesnění problému, abychom ho mohli identifikovat.

1) Kdy přesně jste to vyplňovala (datum+čas, co nejpřesněji)? V poslední době jsme nasazovali více verzí aplikace a musíme zjistit, ve které verzi to bylo.

2) Můžete to zkusit pro jistotu znovu, v aktuální verzi?

3) Pokud to bude stále zlobit i v aktuální verzi, můžeme prosím zaslat screenshot s položkou, kterou s PSČ a obcí, kterou vybíráte? Bohužel nestačí jen PSČ, ale potřebovali bychom to vidět včetně obce, jak je na ukázce, kde je vidět, že je vybrána položka "73801 - Staré Město". Případně to prosím napište třeba slovně.

4) Jaký obecní úřad by měl k tomu Vašemu PSČ správně náležet (adresa)?

Předem děkuji za pomoc.

S pozdravem

Kamil Zmeškal
