### ISSUE TITLE
Validator mne necha vyplnit neodpovidajici PSC a obec

### ISSUE THREAD

**Issue by martenson** [HlidacStatu/Volicsky-Prukaz#7]
60200 je Brno
testovano offline, Chrome, MacOS

![screenshot 2017-09-18 10 12 05](https://user-images.githubusercontent.com/1814954/30546184-dff4ed86-9c59-11e7-9093-393f4a0f5c32.png)

**Comment by jiri-jagos** [comment]
+1 (Firefox 57, Debian testing)

**Comment by zzen** [comment]
Já vim, že už je to po 14 měsících, ale čistím tady issues a zde jsi nejsem jistý, jestli ho zavřít. @martenson - nemělo by být finální rozhodnutí co vyplnit na uživateli, pokud si skutečně přeje "přebít" doporučené hodnoty? Je to konec konců jeho žádost…

**Comment by martenson** [comment]
@zzen Myslim ze mit neexistujici adresu je problem. Pokud nedokazeme adresu validovat, nemeli bychom ukazovat zelena pole 'vse ok', ale naopak rict primo, ze kdyz zadaji spatnou tak to bude (?) mit nasledky. 

Mozna je to prehnane, mozna je v urednim procesu jedno jestli je adresa existujici nebo ne. Neznam ho prilis dobre.

**Comment by woodarius** [comment]
@martenson stránka by měla pokud možno pracovat i v režimu offline a nechceme ji zatěžovat přílišným stahováním dat (číselníků) při startu. Uživateli se budeme snažit pomáhat, nikoliv vkládat přísné restrikce. Aktuálně jsme se rozhodli neimplementovat, v případě negativního feedbacku se k problematice vrátíme. Díky za podnět.

**Comment by martenson** [comment]
@woodarius Diky za odpoved.
