### ISSUE TITLE
validace data me nevaruje o chybe

### ISSUE THREAD

**Issue by martenson** [HlidacStatu/Volicsky-Prukaz#8]
testovano offline, Chrome, MacOS

![screenshot 2017-09-18 10 27 07](https://user-images.githubusercontent.com/1814954/30546938-0594c6cc-9c5c-11e7-82af-2c3dd3dc373c.png)

**Comment by jiri-jagos** [comment]
+1

**Comment by woodarius** [comment]
@jiri-jagos do aktuální verze nelze zadat neexistující datum (zmizí). Lepší formu validací a komunikaci na uživatele řešíme v https://github.com/HlidacStatu/Volicsky-Prukaz/issues/43.
