### ISSUE TITLE
nevyplnila se adresa prislusneho uradu

### ISSUE THREAD

**Issue by martenson** [HlidacStatu/Volicsky-Prukaz#9]
nebylo zobrazeno zadne varovani
testovano offline, MacOS, Chrome

![screenshot 2017-09-18 10 28 47](https://user-images.githubusercontent.com/1814954/30547031-3cf7c10a-9c5c-11e7-8c56-c41a6e44c600.png)

**Comment by iBobik** [comment]
Nevyplnilo se mi to na posledním iOS Safari. Použil jsem autofill.

**Comment by jakubboucek** [comment]
Nai Chrome/Android 7.0

**Comment by iBobik** [comment]
Vyplnilo se mi to, pokud jsem napsal PSČ a klepnul na položku v napovídači. Nevyplnilo se to, když jsem vyplnil číslo a jen přepnul na další pole.

Mimochodem, psaní má hodně dlouhé spoždění, znaky se objeví až s aktualizací napovídače, ne ihned.

**Comment by jiri-jagos** [comment]
+1 (Firefox 57, Debian testing)
Adresa uradu se vubec nevaliduje, nevim jestli je to zamer.


![screenshot_2017-12-01_21-44-01](https://user-images.githubusercontent.com/1304047/33502617-148c2138-d6e1-11e7-84bc-8564b99b8444.png)

**Comment by iBobik** [comment]
@michalblaha Právě jsem na tohle narazil na produkci. Je to nasazené?

**Comment by michalblaha** [comment]
Na co? ze se adresa nevaliduje nebo pomaly napovidac psc?

**Comment by iBobik** [comment]
Že se nevyplní adresa úřadu pokud se neklikne na našeptávač PSČ.



Honza Pobořil
https://honza.poboril.cz

**Comment by jakubboucek** [comment]
On je tam trochu problém, že PSČ nemusí být jednoznačné, takže na něj může spadat klidně více úřadů. Hlavně ve velkých městech.

**Comment by iBobik** [comment]
To je důvod proč tam je ten bug? :-)

Jan Pobořil
https://honza.poboril.cz/

3. 12. 2017 v 23:07, Jakub Bouček <notifications@github.com>:

**Comment by michalblaha** [comment]
PSC by melo sedet i ve velkych mestech, alespon podle zkusenosti s parlamentnimi volbami. Jednoznacny ciselnik se mi ze statu nedari dostat. 
na psc z ciselniku se kliknout musi, bohuzel to zatim jinak nejde.

**Comment by iBobik** [comment]
Aha, takže to je spíše na samostatné issue: #32
